common:
  seed: 42
  device: 3

runimp:
  batch_size: 1024
  in_memory: True
  epochs: 100
  dropout: 0.5
  hidden_channels: 1024

runimp_option1:
  batch_size: 1024
  in_memory: True
  epochs: 100
  dropout: 0.5
  hidden_channels: 1024

mag240m:
  root: '/lfs/hyperturing1/0/vid/mag240m'

  heterogenous_neighbor_sampler:
    original:
      sizes:
        paper_paper: [25,  15]
        paper_author: [10, 10]
        author_paper: [10, 10]
        author_institution: [5, 5]
        institution_author: [5, 5]
    
    option1:
      sampling_budget: [35, 40]
      sizes: # this is calculated
        paper_paper: [0.37575599,  0.37575599]
        paper_author: [0.30705104, 0.30705104]
        author_paper: [0.30705104, 0.30705104]
        author_institution: [0.00507096, 0.00507096]
        institution_author: [0.00507096, 0.00507096]
